modsets:
  - core:
    name: "SOCOMD_Core/@socomd_core"
    mods:
      - "./core/socomd_core"
      - "./core/socomd_zeus"
      - "./core/socomd_medical"
      - "./core/3rd_party/sa_advancedslingloading"
      - "./core/3rd_party/socomd_asorgs"
      - "./core/3rd_party/socomd_asorvs"
      - "./core/3rd_party/socomd_gcam"
      - "./core/3rd_party/vqi_c130"
      - "./core/3rd_party/vqi_halo"
      - "./core/3rd_party/grad_boc"
      - "./core/3rd_party/plp_containers"
      - "./core/3rd_party/fgs_prv13"
      - "./core/3rd_party/fgs_rsp6"
      - "./core/3rd_party/usp_interactions_uniforms"
      - "./data/socomd_data_core"
      - "./data/kat_data"
      - "./misc/socomd_missions"
  - content:
    name: "SOCOMD_Core/@socomd_content"
    mods:
      - "./modsets/socomd_content"
      - "./compats/socomd_compat_cup"
      - "./compats/socomd_compat_h60"
      - "./compats/socomd_compat_usp"
      - "./data/socomd_data_cup"
      - "./data/cos_content"
  - hardcore:
    name: "SOCOMD_Extra/@socomd_hardcore"
    mods:
      - "./modsets/socomd_hardcore"
