modsets:
  - core:
    name: "SOCOMD_Core/@socomd_core"
    mods:
      - "./core/socomd_core"
      - "./core/socomd_zeus"
      - "./core/3rd_party/ar_advancedrappelling"
      - "./core/3rd_party/sa_advancedslingloading"
      - "./core/3rd_party/socomd_asorgs"
      - "./core/3rd_party/socomd_asorvs"
      - "./core/3rd_party/socomd_gcam"
      - "./data/socomd_data_core"
      - "./misc/socomd_missions"
  - content:
    name: "SOCOMD_Core/@socomd_content"
    mods:
      - "./modsets/socomd_content"
      - "./compats/socomd_compat_cup"
      - "./data/socomd_data_cup"
  - hardcore:
    name: "SOCOMD_Extra/@socomd_hardcore"
    mods:
      - "./modsets/socomd_hardcore"
