modsets:
  - core:
    name: "SOCOMD_Core/@socomd_core"
    mods:
  - content:
    name: "SOCOMD_Core/@socomd_content"
    mods:
      - "./3rd_party/cos_content"
      - "./core/3rd_party/sa_advancedslingloading"
      - "./core/3rd_party/socomd_asorvs"
      - "./core/3rd_party/grad_boc"
      - "./core/3rd_party/fgs_prv13"
      - "./core/3rd_party/fgs_rsp6"
      - "./core/3rd_party/usp_interactions_uniforms"
  # - hardcore:
  #   name: "SOCOMD_Extra/@socomd_hardcore"
  #   mods:
  #     - "./modsets/socomd_hardcore"
