modsets:
  - core:
    name: "SOCOMD_Core/@socomd_core"
    mods:
      - "./core/socomd_core"
      - "./core/socomd_zeus"
      - "./core/3rd_party/ar_advancedrappelling"
      - "./core/3rd_party/sa_advancedslingloading"
      - "./core/3rd_party/socomd_asorgs"
      - "./core/3rd_party/socomd_asorvs"
      - "./core/3rd_party/socomd_gcam"
      - "./core/3rd_party/lav25/vtn_armorw_lav25_cf"
      - "./core/3rd_party/lav25/vtn_armorw_lav25_md"
      - "./core/3rd_party/lav25/vtn_armorw_lav25_opt"
      - "./core/3rd_party/lav25/vtn_armorw_lav25_tx"
      - "./core/3rd_party/lav25/vtn_armore_whl_brdm2_opt"
      - "./core/3rd_party/lav25/vtn_wpnw_m240_tx"
      - "./core/3rd_party/lav25/vtn_wheeledw_m1151_tx"
      - "./core/3rd_party/lav25/vtn_wheelede_kamaz5350_tx"
      - "./core/3rd_party/lav25/vtn_bp_ilbe_tx"
      - "./core/3rd_party/lav25/vtn_materials"
      - "./core/3rd_party/lav25/vtn_nabojnice_tx"
      - "./core/3rd_party/lav25/vtn_tracer_tx"
      - "./data/socomd_data_core"
      - "./misc/socomd_missions"
  - content:
    name: "SOCOMD_Core/@socomd_content"
    mods:
      - "./modsets/socomd_content"
      - "./compats/socomd_compat_cup"
      - "./data/socomd_data_cup"
  - hardcore:
    name: "SOCOMD_Extra/@socomd_hardcore"
    mods:
      - "./modsets/socomd_hardcore"
