modsets:
  - core:
    name: "@scomd_core"
    mods:
      - "./core/socomd_core"
      - "./core/socomd_zeus"
      - "./core/3rd_party/ar_advancedrapelling"
      - "./core/3rd_party/sa_advancedslingloading"
      - "./core/3rd_party/socomd_asorgs"
      - "./core/3rd_party/socomd_asorvs"
      - "./core/3rd_party/socomd_gcam"
      - "./data/socomd_data_core"
  - content:
    name: "@socomd_content"
    mods:
      - "./modsets/socomd_content"
      - "./compats/socomd_compat_cup"
      - "./data/socomd_data_cup"
  - hardcore:
    name: "@socomd_hardcore"
    mods:
      - "./modsets/socomd_hardcore"
  - jointOp:
    name: "@socomd_jointOps"
    mods:
      - "./modsets/socomd_160th"
